# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tts.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttts.proto\x12\x03tts\"\x8c\x01\n\x11SynthesizeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05voice\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\r\n\x05speed\x18\x04 \x01(\x02\x12\r\n\x05pitch\x18\x05 \x01(\x02\x12\x15\n\routput_format\x18\x06 \x01(\t\x12\x13\n\x0bsample_rate\x18\x07 \x01(\x05\"\x87\x01\n\x12SynthesizeResponse\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x10\n\x08\x64uration\x18\x02 \x01(\x02\x12\x13\n\x0bsample_rate\x18\x03 \x01(\x05\x12\x0e\n\x06\x66ormat\x18\x04 \x01(\t\x12\x0f\n\x07success\x18\x05 \x01(\x08\x12\x15\n\rerror_message\x18\x06 \x01(\t\"\\\n\nAudioChunk\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x10\n\x08is_final\x18\x02 \x01(\x08\x12\x11\n\ttimestamp\x18\x03 \x01(\x02\x12\x15\n\rerror_message\x18\x04 \x01(\t\"$\n\x10GetVoicesRequest\x12\x10\n\x08language\x18\x01 \x01(\t\"^\n\x05Voice\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x0e\n\x06gender\x18\x03 \x01(\t\x12\x0f\n\x07quality\x18\x04 \x01(\t\x12\x14\n\x0csample_rates\x18\x05 \x03(\x05\"W\n\x11GetVoicesResponse\x12\x1a\n\x06voices\x18\x01 \x03(\x0b\x32\n.tts.Voice\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t2\xcb\x01\n\x0cTextToSpeech\x12=\n\nSynthesize\x12\x16.tts.SynthesizeRequest\x1a\x17.tts.SynthesizeResponse\x12@\n\x13StreamingSynthesize\x12\x16.tts.SynthesizeRequest\x1a\x0f.tts.AudioChunk0\x01\x12:\n\tGetVoices\x12\x15.tts.GetVoicesRequest\x1a\x16.tts.GetVoicesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tts_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SYNTHESIZEREQUEST']._serialized_start=19
  _globals['_SYNTHESIZEREQUEST']._serialized_end=159
  _globals['_SYNTHESIZERESPONSE']._serialized_start=162
  _globals['_SYNTHESIZERESPONSE']._serialized_end=297
  _globals['_AUDIOCHUNK']._serialized_start=299
  _globals['_AUDIOCHUNK']._serialized_end=391
  _globals['_GETVOICESREQUEST']._serialized_start=393
  _globals['_GETVOICESREQUEST']._serialized_end=429
  _globals['_VOICE']._serialized_start=431
  _globals['_VOICE']._serialized_end=525
  _globals['_GETVOICESRESPONSE']._serialized_start=527
  _globals['_GETVOICESRESPONSE']._serialized_end=614
  _globals['_TEXTTOSPEECH']._serialized_start=617
  _globals['_TEXTTOSPEECH']._serialized_end=820
# @@protoc_insertion_point(module_scope)
